id = "ejx"
name = "EJX"
version = "0.0.1"
schema_version = 1
authors = ["Ben Ehmke"]
description = "EJX template support for Zed"
repository = "https://github.com/bemky/zed-ejx"

[grammars.embedded_javascript_template]
repository = "https://github.com/bemky/tree-sitter-embedded-template"
commit = "d2cd4aae8dc698269620d4d57c975c68fd9750a3"

[icons]
"*.ejx" = "html"
