id = "ejx"
name = "EJX"
version = "0.0.1"
schema_version = 1
authors = ["Ben Ehmke"]
description = "EJX template support for Zed"
repository = "https://github.com/bemky/zed-ejx"

[grammars.embedded_template]
repository = "https://github.com/bemky/tree-sitter-embedded-template"
commit = "20ce35a491837cd9add3b27e84e3710a1abca109"

[icons]
"*.ejx" = "html"
